on:
  push:

name: Build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: riscv32imac-unknown-none-elf
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Store binary
        uses: actions/upload-artifact@v2
        with:
          name: hifive-flashloader
          path: target/riscv32imac-unknown-none-elf/release/hifive-flashloader

  create_target_desc:
    name: Create target description file
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download flashloader binary
        uses: actions/download-artifact@v2
        with:
          name: hifive-flashloader

      - name: Install target-gen tool
        uses: actions-rs/cargo@va
        with:
          command: install
          args: --git https://github.com/probe-rs/target-gen

      - name: Create target description file
        run: target-gen elf hifive-flashloader hifive_flashloader.yml
